name: caller-workflow

on:
  push:
    branches: [main]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: ${{ secrets.PROD_ENV_NAME }}
      # ^^ callers can reference an org secret ^^